const AXIOS_ERROR_CODES = {
  ERR_NETWORK: "ERR_NETWORK",
  ERR_CANCELED: "ERR_CANCELED",
  ERR_BAD_REQUEST: "ERR_BAD_REQUEST",
  // FORBIDDEN: 403,
  // NOT_FOUND: 404,
  // INTERNAL_SERVER_ERROR: 500,
};

const ERROR_STATUS_CODES = {
  "400": 400,
  "401": 401,
};

export { AXIOS_ERROR_CODES, ERROR_STATUS_CODES };
